name: Renovate

on:
  schedule:
    - cron: '0 2 * * 0'  # Every Sunday at 2 AM UTC
  workflow_dispatch:

jobs:
  renovate:
    name: Run Renovate Bot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.17
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate.json
