name: Renovate

on:
  schedule:
    - cron: '0 2 * * 0'  # Runs weekly on Sundays at 2 AM UTC
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.17
        with:
          configurationFile: renovate.json
